---
- name: tao interface loopback
  hosts: all
  gather_facts: no

  tasks:
    - name: Create loopback
      ios_l3_interface:
        ipv4: {{ item.number }}"/24"
        name: "{{ item.name }}"
      with_items:
        - { number: "10.0.1.1", name: "loopback1" }
        - { number: "10.0.1.2", name: "loopback2" }
        - { number: "10.0.1.3", name: "loopback3" }

    - name: Show loopback
      ios_command:
        commands:
          - show ip int brief
      register: show_loopback

    - debug: var=show_loopback.stdout_lines
